# 应用服务 WEB 访问端口
server:
  port: 8090
log:
#  path: /Users/songhongxing/fhjs/logs/
  path: /home/web/data/fhjs/logs
# 应用名称
spring:
  application:
    name: fhjs
  data:
    mongodb:
      host: 101.43.157.72
      port: 27017
      database: msjs
      username: songhongxing
      password: xing520025
      authentication-database: admin
    task:
      scheduling:
        pool:
          size: 10
        thread-name-prefix: hanhan
      execution:
        shutdown:
          #        线程关闭时是否等所有任务结束
          await-termination: false
          #        线程最大的等待时间，防止线程陷入循环关不掉
          await-termination-period: 10s
#  datasource:
#    druid:
#      game:
##        driver-class-name: com.mysql.jdbc.Driver
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://101.43.157.72:3306/xygame?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
#        username: root
#        password: Xing@520025!
#        # 连接池其他配置
#        remove-abandoned-timeout: 7200
#        # 初始连接数
#        initial-size: 10
#        # 最大连接数
#        max-active: 100
#        min-idle: 10
#        max-wait: 60000
#        pool-prepared-statements: true
#        max-pool-prepared-statement-per-connection-size: 20
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 300000
#        validation-query: SELECT 1 FROM DUAL
#        test-while-idle: true
#        test-on-borrow: false
#        test-on-return: false
#        stat-view-servlet:
#          enabled: true
#          url-pattern: /druid/*
#        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#        filter:
#          stat:
#            log-slow-sql: true
#            slow-sql-millis: 1000
#            merge-sql: false
#          wall:
#            config:
#              multi-statement-allow: true
#        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000




